-   id: docker-jenkinslint
    name: jenkinslint (via docker_image)
    description: jenkinslint, but provided by docker
    entry: --entrypoint /usr/local/bin/run-jflint.sh askulkarni2/jenkinslint:latest
    language: docker_image