version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install dependencies
          command: pip3 install --user pre-commit
      - run:
          name: Build Docker image
          command: |
            make build
      - run:
          name: Test Jenkinsfile
          command: |
            make test
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            make push